[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
flipper = "5958qddzZjU34CHUD4bisVBiYgDQ6EREwBLgpbVaSLX7"
mock_meteora = "699YWVLRa4T5Mxs3iNJGnpwP24JNckt25vW1pEMc5xrA"
mock_raydium = "FmQ6x78hRZyXJcofk7NSHx9tvPEtEonjsMdAX6FQw7wm"
mock_whirlpools = "Fa6sgRmBda2UJpBT1tV3bq27JkLjuRYvnt6TxWqAJT5F"



[programs.localnet]
flipper = "5958qddzZjU34CHUD4bisVBiYgDQ6EREwBLgpbVaSLX7"
mock_meteora = "699YWVLRa4T5Mxs3iNJGnpwP24JNckt25vW1pEMc5xrA"
mock_raydium = "FmQ6x78hRZyXJcofk7NSHx9tvPEtEonjsMdAX6FQw7wm"
mock_whirlpools = "Fa6sgRmBda2UJpBT1tV3bq27JkLjuRYvnt6TxWqAJT5F"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
