[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
flipper = "fLpRcgQSJxKeeUogb6M7bWe1iyYQbahjGXGwr4HgHit"
mock_meteora = "Ch3ntiZFPQYozofrWrjkUcKiyVrmmE5i1YodBDd7a5ax"
mock_raydium = "HTg2aCPRCYMMEbkx59TmQcyp4LcGZScoYksCBwJAfLNJ"
mock_whirlpools = "CZUz9mp2h2gStQ7tKzvAjyCvW3tUgBXcSA6E6atHXxCD"

[programs.localnet]
flipper = "fLpRcgQSJxKeeUogb6M7bWe1iyYQbahjGXGwr4HgHit"
mock_meteora = "Ch3ntiZFPQYozofrWrjkUcKiyVrmmE5i1YodBDd7a5ax"
mock_raydium = "HTg2aCPRCYMMEbkx59TmQcyp4LcGZScoYksCBwJAfLNJ"
mock_whirlpools = "CZUz9mp2h2gStQ7tKzvAjyCvW3tUgBXcSA6E6atHXxCD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/flpp-staging.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
