[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
flipper = "DEmNWvQ6d5XrhUbeysVRiesSsnLyJNzAXm3mmExc2Sy6"
mock_raydium = "CAiM1WWDmEjQz892ZYCtrUJUFVQfkC56LuLNLWPYVaCc"

[programs.localnet]
flipper = "5958qddzZjU34CHUD4bisVBiYgDQ6EREwBLgpbVaSLX7"
mock_meteora = "3os6rCTWfryeaAzCd3Qicj9x4mbYwcnoByarPhcUYM8P"
mock_raydium = "FmQ6x78hRZyXJcofk7NSHx9tvPEtEonjsMdAX6FQw7wm"
mock_whirlpools = "2KQKFVr4CUoUHJjKaMrJYwHy7dirPRmjPj9QyZgmPXf3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
