[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
flipper = "fLpRcgQSJxKeeUogb6M7bWe1iyYQbahjGXGwr4HgHit"
mock_jupiter = "EbgGVffJ6wAsJUj73jkZaNLRgXyFLTuPDzGvRGyT39wv"
mock_meteora = "3gD2eXxYMEqYsamgosxKb7MdVqgeVYDuSDKdnT9jDTr1"
mock_raydium = "2vHpsa2cyo2L8uBmsx1ht2ExZwcnxDeYRZFJCT5oW5r6"
mock_whirlpools = "EZiRzSsL6uEC7DoNSuLqpE1WoHXFLQARVSoJaFgLBCYY"

[programs.localnet]
flipper = "fLpRcgQSJxKeeUogb6M7bWe1iyYQbahjGXGwr4HgHit"
mock_jupiter = "EbgGVffJ6wAsJUj73jkZaNLRgXyFLTuPDzGvRGyT39wv"
mock_meteora = "3gD2eXxYMEqYsamgosxKb7MdVqgeVYDuSDKdnT9jDTr1"
mock_raydium = "2vHpsa2cyo2L8uBmsx1ht2ExZwcnxDeYRZFJCT5oW5r6"
mock_whirlpools = "EZiRzSsL6uEC7DoNSuLqpE1WoHXFLQARVSoJaFgLBCYY"

[programs.mainnet]
flipper = "fLpRcgQSJxKeeUogb6M7bWe1iyYQbahjGXGwr4HgHit"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/fpp-staging.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
